(() => {
'use strict';
function n(v){let x=Number(v);return Number.isFinite(x)?x:null}
function style(){if(document.getElementById('phStyle'))return;let s=document.createElement('style');s.id='phStyle';s.textContent='.pressure-history{margin-top:14px}.history-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.history-chart{border:1px solid rgba(75,124,153,.25);border-radius:14px;padding:12px}.history-chart svg{width:100%;height:140px}.history-chart polyline{fill:none;stroke:currentColor;stroke-width:2}.history-chart circle{fill:currentColor}@media(max-width:850px){.history-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function daily(xs){let m=new Map();xs.forEach(x=>m.set(String(x.timestamp||'').slice(0,10),x));return [...m.values()].slice(-14)}
function chart(title,xs,port){let vals=xs.map(x=>n(x.ports?.[port]?.potentialQueueRatio)||0),max=Math.max(1,...vals),W=500,H=120,p=15,den=Math.max(1,xs.length-1),pts=vals.map((v,i)=>[p+(W-2*p)*(i/den),H-p-(H-2*p)*(v/max),v]);return `<div class="history-chart"><h3>${title}</h3><small>ضغط الدخول المحتمل — آخر ${xs.length} أيام</small><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><polyline points="${pts.map(q=>q[0]+','+q[1]).join(' ')}"/>${pts.map(q=>`<circle cx="${q[0]}" cy="${q[1]}" r="3"><title>${q[2].toFixed(2)}</title></circle>`).join('')}</svg></div>`}
async function run(){style();let sec=document.getElementById('pressure');if(!sec)return;let p=document.getElementById('pressureHistoryPanel');if(!p){p=document.createElement('article');p.id='pressureHistoryPanel';p.className='panel pressure-history';p.innerHTML='<div class="panel-head"><div><span class="kicker">Port Pressure History</span><h2>اتجاه الضغط عبر الزمن</h2></div><span class="pill" id="pressureHistoryCount">—</span></div><div id="pressureHistoryCharts" class="history-grid"></div><div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>مصراتة</th><th>بنغازي</th><th>Post-Port مصراتة</th><th>Post-Port بنغازي</th></tr></thead><tbody id="pressureHistoryRows"></tbody></table></div>';sec.appendChild(p)}let h=await fetch(`port_pressure_history.json?t=${Date.now()}`,{cache:'no-store'}).then(r=>r.json()),all=h.snapshots||[],d=daily(all);document.getElementById('pressureHistoryCount').textContent=`${all.length} لقطة محفوظة`;document.getElementById('pressureHistoryCharts').innerHTML=chart('مصراتة',d,'Misurata')+chart('بنغازي',d,'Benghazi');document.getElementById('pressureHistoryRows').innerHTML=d.slice().reverse().map(x=>{let m=x.ports?.Misurata||{},b=x.ports?.Benghazi||{};return `<tr><td>${String(x.timestamp||'').slice(0,10)}</td><td>${n(m.potentialQueueRatio)?.toFixed(2)??'—'}</td><td>${n(b.potentialQueueRatio)?.toFixed(2)??'—'}</td><td>${m.postPortActive??'—'}</td><td>${b.postPortActive??'—'}</td></tr>`}).join('')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();document.addEventListener('click',e=>{if(e.target.closest?.('.nav[data-view="pressure"]'))setTimeout(run,80)});
})();
