(() => {'use strict';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const f=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
const pa=p=>p==='Misurata'?'مصراتة':'بنغازي';
const la=v=>v==='High'?'مرتفع':v==='Medium'?'متوسط':v==='Low'?'منخفض':'غير معروف';
const c=(l,v,s)=>`<div class="pressure-mini"><small>${e(l)}</small><b>${e(v)}</b><span>${e(s||'')}</span></div>`;
function panel(m){if(!m)return'';const stay=Number.isFinite(Number(m.avgPortStayProxyDays))?`${f(m.avgPortStayProxyDays,1)} يوم`:'—';return `<article class="panel pressure-port"><div class="panel-head"><div><span class="kicker">Phase-Aware Pressure</span><h2>${pa(m.port)}</h2></div><span class="pressure-level ${String(m.pressureLevel||'').toLowerCase()}">${la(m.pressureLevel)}</span></div><div class="pressure-metrics">${c('الوصول / يوم',f(m.arrivalsPerDay,2),`${m.arrivals||0} زيارة`)}${c('انتظار مؤكد ÷ الداخل',f(m.confirmedQueueRatio,2),`${m.confirmedPrePort||0} قبل الدخول / ${m.currentInPort||0} داخل`)}${c('ضغط محتمل ÷ الداخل',f(m.potentialQueueRatio,2),`${(m.confirmedPrePort||0)+(m.unknownAnchorage||0)} قبل/غير محسوم`)}${c('بعد المغادرة — مستبعد',String(m.postPortActive||0),'لا يدخل في طابور الدخول')}${c('غير محسوم',String(m.unknownAnchorage||0),'احتمال فقط')}${c('متوسط البقاء المرصود',stay,'Port Stay Proxy')}</div><div class="pressure-reason">${e(m.likelyReason||'')}</div></article>`}
function render(d){const b=d?.portPressure,r=document.getElementById('pressurePanels');if(!r)return;if(!b||!b.ports){r.innerHTML='<article class="panel"><p class="muted">لم تُحسب المؤشرات بعد.</p></article>';return}r.innerHTML=panel(b.ports.Misurata)+panel(b.ports.Benghazi);const p=document.getElementById('pressurePeriod');if(p)p.textContent=`${b.periodStart||'—'} → ${b.periodEnd||'—'} · ${b.effectiveDays||0} أيام`;const n=document.getElementById('pressureMethod');if(n)n.textContent='بعد مغادرة الميناء مستبعد من ضغط الدخول. المؤكد = PRE_PORT فقط، والمحتمل = PRE_PORT + غير محسوم.'}
async function load(){try{const r=await fetch(`data.json?t=${Date.now()}`,{cache:'no-store'});render(await r.json())}catch(x){console.error(x)}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();document.addEventListener('click',x=>{if(x.target.closest?.('.nav[data-view="pressure"]'))setTimeout(load,50)});})();
